FROM node:9-alpine

WORKDIR /opt/app/

COPY package.json yarn.lock ./

RUN yarn --prod --check-files --frozen-lockfile && \
    chmod -R 777 node_modules

COPY . ./

RUN yarn prod:client && \
    rm -rf src assets

CMD yarn prod

